# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/bd/OV5640_TFT/ip/OV5640_TFT_AXI_Frame_Difference_0_0/OV5640_TFT_AXI_Frame_Difference_0_0.xci
# IP: The module: 'OV5640_TFT_AXI_Frame_Difference_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_equ_fifo/hist_equ_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_fifo || ORIG_REF_NAME==hist_equ_fifo} -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_equ_remap_bram/hist_equ_remap_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_remap_bram || ORIG_REF_NAME==hist_equ_remap_bram} -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_equ_div/hist_equ_div.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_div || ORIG_REF_NAME==hist_equ_div} -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/multiplier/multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiplier || ORIG_REF_NAME==multiplier} -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_static_bram/hist_static_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_static_bram || ORIG_REF_NAME==hist_static_bram} -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/video_fifo/video_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==video_fifo || ORIG_REF_NAME==video_fifo} -quiet] -quiet

# XDC: d:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_equ_fifo/hist_equ_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hist_equ_fifo || ORIG_REF_NAME==hist_equ_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_equ_remap_bram/hist_equ_remap_bram_ooc.xdc

# XDC: d:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_static_bram/hist_static_bram_ooc.xdc

# XDC: d:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/video_fifo/video_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==video_fifo || ORIG_REF_NAME==video_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/bd/OV5640_TFT/ip/OV5640_TFT_AXI_Frame_Difference_0_0/OV5640_TFT_AXI_Frame_Difference_0_0.xci
# IP: The module: 'OV5640_TFT_AXI_Frame_Difference_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_equ_fifo/hist_equ_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_fifo || ORIG_REF_NAME==hist_equ_fifo} -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_equ_remap_bram/hist_equ_remap_bram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_remap_bram || ORIG_REF_NAME==hist_equ_remap_bram} -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_equ_div/hist_equ_div.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_div || ORIG_REF_NAME==hist_equ_div} -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/multiplier/multiplier.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiplier || ORIG_REF_NAME==multiplier} -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_static_bram/hist_static_bram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_static_bram || ORIG_REF_NAME==hist_static_bram} -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/video_fifo/video_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==video_fifo || ORIG_REF_NAME==video_fifo} -quiet] -quiet

# XDC: d:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_equ_fifo/hist_equ_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hist_equ_fifo || ORIG_REF_NAME==hist_equ_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_equ_remap_bram/hist_equ_remap_bram_ooc.xdc

# XDC: d:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/hist_static_bram/hist_static_bram_ooc.xdc

# XDC: d:/VivadoProject/OV5640_TFT_Back/OV5640_TFT/OV5640_TFT.srcs/sources_1/ip/video_fifo/video_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==video_fifo || ORIG_REF_NAME==video_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
