# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VivadoProject/OV5640_TFT/OV5640_TFT.srcs/sources_1/bd/OV5640_TFT/ip/OV5640_TFT_v_tc_0_0/OV5640_TFT_v_tc_0_0.xci
# IP: The module: 'OV5640_TFT_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/OV5640_TFT/OV5640_TFT.srcs/sources_1/bd/OV5640_TFT/ip/OV5640_TFT_v_tc_0_0/OV5640_TFT_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'OV5640_TFT_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/VivadoProject/OV5640_TFT/OV5640_TFT.srcs/sources_1/bd/OV5640_TFT/ip/OV5640_TFT_v_tc_0_0/OV5640_TFT_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OV5640_TFT_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/VivadoProject/OV5640_TFT/OV5640_TFT.srcs/sources_1/bd/OV5640_TFT/ip/OV5640_TFT_v_tc_0_0/OV5640_TFT_v_tc_0_0.xci
# IP: The module: 'OV5640_TFT_v_tc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/OV5640_TFT/OV5640_TFT.srcs/sources_1/bd/OV5640_TFT/ip/OV5640_TFT_v_tc_0_0/OV5640_TFT_v_tc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'OV5640_TFT_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/VivadoProject/OV5640_TFT/OV5640_TFT.srcs/sources_1/bd/OV5640_TFT/ip/OV5640_TFT_v_tc_0_0/OV5640_TFT_v_tc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OV5640_TFT_v_tc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
