# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/VivadoProject/Camera_Detect/Camera_Detect.srcs/constrs_1/new/system.xdc

# IP: ip/hist_equ_fifo/hist_equ_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_fifo || ORIG_REF_NAME==hist_equ_fifo} -quiet] -quiet

# IP: ip/hist_equ_remap_bram/hist_equ_remap_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_remap_bram || ORIG_REF_NAME==hist_equ_remap_bram} -quiet] -quiet

# IP: ip/hist_equ_div/hist_equ_div.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_div || ORIG_REF_NAME==hist_equ_div} -quiet] -quiet

# IP: ip/multiplier/multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiplier || ORIG_REF_NAME==multiplier} -quiet] -quiet

# IP: ip/hist_static_bram/hist_static_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_static_bram || ORIG_REF_NAME==hist_static_bram} -quiet] -quiet

# IP: ip/video_fifo/video_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==video_fifo || ORIG_REF_NAME==video_fifo} -quiet] -quiet

# Block Designs: bd/OV5640_TFT/OV5640_TFT.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT || ORIG_REF_NAME==OV5640_TFT} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_processing_system7_0_0/OV5640_TFT_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_processing_system7_0_0 || ORIG_REF_NAME==OV5640_TFT_processing_system7_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_v_axi4s_vid_out_0_0/OV5640_TFT_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==OV5640_TFT_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_v_tc_0_0/OV5640_TFT_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_v_tc_0_0 || ORIG_REF_NAME==OV5640_TFT_v_tc_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_axi_vdma_0_0/OV5640_TFT_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_axi_vdma_0_0 || ORIG_REF_NAME==OV5640_TFT_axi_vdma_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_v_vid_in_axi4s_0_0/OV5640_TFT_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==OV5640_TFT_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_rgb2lcd_0_0/OV5640_TFT_rgb2lcd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_rgb2lcd_0_0 || ORIG_REF_NAME==OV5640_TFT_rgb2lcd_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_axi_dynclk_0_0/OV5640_TFT_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_axi_dynclk_0_0 || ORIG_REF_NAME==OV5640_TFT_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_axi_smc_0/OV5640_TFT_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_axi_smc_0 || ORIG_REF_NAME==OV5640_TFT_axi_smc_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_rst_ps7_0_100M_0/OV5640_TFT_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_rst_ps7_0_100M_0 || ORIG_REF_NAME==OV5640_TFT_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_xbar_0/OV5640_TFT_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_xbar_0 || ORIG_REF_NAME==OV5640_TFT_xbar_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_ps7_0_axi_periph_0/OV5640_TFT_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_ps7_0_axi_periph_0 || ORIG_REF_NAME==OV5640_TFT_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_OV5640_Data_0_0/OV5640_TFT_OV5640_Data_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_OV5640_Data_0_0 || ORIG_REF_NAME==OV5640_TFT_OV5640_Data_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_clk_wiz_0_0/OV5640_TFT_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_clk_wiz_0_0 || ORIG_REF_NAME==OV5640_TFT_clk_wiz_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_axi_vdma_1_1/OV5640_TFT_axi_vdma_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_axi_vdma_1_1 || ORIG_REF_NAME==OV5640_TFT_axi_vdma_1_1} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_axis_broadcaster_0_0/OV5640_TFT_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_axis_broadcaster_0_0 || ORIG_REF_NAME==OV5640_TFT_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_AXI_Frame_Difference_0_0/OV5640_TFT_AXI_Frame_Difference_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_AXI_Frame_Difference_0_0 || ORIG_REF_NAME==OV5640_TFT_AXI_Frame_Difference_0_0} -quiet] -quiet

# IP: ip/hist_equ_fifo/hist_equ_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_fifo || ORIG_REF_NAME==hist_equ_fifo} -quiet] -quiet

# IP: ip/hist_equ_remap_bram/hist_equ_remap_bram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_remap_bram || ORIG_REF_NAME==hist_equ_remap_bram} -quiet] -quiet

# IP: ip/hist_equ_div/hist_equ_div.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_equ_div || ORIG_REF_NAME==hist_equ_div} -quiet] -quiet

# IP: ip/multiplier/multiplier.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiplier || ORIG_REF_NAME==multiplier} -quiet] -quiet

# IP: ip/hist_static_bram/hist_static_bram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hist_static_bram || ORIG_REF_NAME==hist_static_bram} -quiet] -quiet

# IP: ip/video_fifo/video_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==video_fifo || ORIG_REF_NAME==video_fifo} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_rgb888to565_0_0/OV5640_TFT_rgb888to565_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_rgb888to565_0_0 || ORIG_REF_NAME==OV5640_TFT_rgb888to565_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_rgb565to888_0_0/OV5640_TFT_rgb565to888_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_rgb565to888_0_0 || ORIG_REF_NAME==OV5640_TFT_rgb565to888_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_bram_0_1/OV5640_TFT_bram_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_bram_0_1 || ORIG_REF_NAME==OV5640_TFT_bram_0_1} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_blk_mem_gen_0_0/OV5640_TFT_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_blk_mem_gen_0_0 || ORIG_REF_NAME==OV5640_TFT_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_axi_bram_ctrl_0_0/OV5640_TFT_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_axi_bram_ctrl_0_0 || ORIG_REF_NAME==OV5640_TFT_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_auto_pc_4/OV5640_TFT_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_auto_pc_4 || ORIG_REF_NAME==OV5640_TFT_auto_pc_4} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_auto_pc_0/OV5640_TFT_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_auto_pc_0 || ORIG_REF_NAME==OV5640_TFT_auto_pc_0} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_auto_pc_1/OV5640_TFT_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_auto_pc_1 || ORIG_REF_NAME==OV5640_TFT_auto_pc_1} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_auto_pc_2/OV5640_TFT_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_auto_pc_2 || ORIG_REF_NAME==OV5640_TFT_auto_pc_2} -quiet] -quiet

# IP: bd/OV5640_TFT/ip/OV5640_TFT_auto_pc_3/OV5640_TFT_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV5640_TFT_auto_pc_3 || ORIG_REF_NAME==OV5640_TFT_auto_pc_3} -quiet] -quiet

# XDC: ip/hist_equ_fifo/hist_equ_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hist_equ_fifo || ORIG_REF_NAME==hist_equ_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/hist_equ_remap_bram/hist_equ_remap_bram_ooc.xdc

# XDC: ip/hist_static_bram/hist_static_bram_ooc.xdc

# XDC: ip/video_fifo/video_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==video_fifo || ORIG_REF_NAME==video_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/hist_equ_fifo/hist_equ_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hist_equ_fifo || ORIG_REF_NAME==hist_equ_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/hist_equ_remap_bram/hist_equ_remap_bram_ooc.xdc

# XDC: ip/hist_static_bram/hist_static_bram_ooc.xdc

# XDC: ip/video_fifo/video_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==video_fifo || ORIG_REF_NAME==video_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/OV5640_TFT/OV5640_TFT_ooc.xdc
